theme:
  activeBorderColor:
    - '#82aaff'
    - bold
  inactiveBorderColor:
    - '#7a88cf'
  optionsTextColor:
    - '#82aaff'
  selectedLineBgColor:
    - '#444a73'
  cherryPickedCommitBgColor:
    - '#2f334d'
  cherryPickedCommitFgColor:
    - '#82aaff'
  unstagedChangesColor:
    - '#ff757f'
  defaultFgColor:
    - '#c8d3f5'
  searchingActiveBorderColor:
    - '#ffc777'
    - bold
  markedBaseCommitBgColor:
    - '#ffc777'
  markedBaseCommitFgColor:
    - '#212337'

authorColors:
  '*': '#c099ff'
