command_timeout = 1000

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[java]
symbol = "ğŸ«–"

[nodejs]
symbol = "ğŸ¦–"

[ruby]
symbol = "ğŸ”»"

[scala]
symbol = "ğŸªœ"
